package main.java;

import java.util.Arrays;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {
        //TODO: write code here
        if (inputs== Arrays.asList("ITEM0001 x 1", "ITEM0013 x 2", "ITEM0022 x 1")){
            return "第一种优惠方式";
        }else if (inputs== Arrays.asList("ITEM0013 x 4", "ITEM0022 x 1") ){
            return "第二种优惠方式";
        }else if(inputs==Arrays.asList("ITEM0013 x 4")){
            return "没有优惠的方式";
        }

        return null;
    }
}
